name: Build, Test, and Release

on:
  push:
    tags:
      - 'v*.*.*'  # Trigger this workflow only on version tags (e.g., v1.0.0)

jobs:
  test:
    name: Run Tests on Debian
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'  # Specify your Go version here

      - name: Run Go tests
        run: |
          go test -v ./...

  build:
    name: Build for different architectures
    runs-on: ubuntu-latest
    needs: test  # Ensure this runs only after the test job succeeds

    strategy:
      matrix:
        goarch: [amd64, arm, arm64]  # Different architectures to build for
        goos: [linux]    # Add more OS if needed

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'  # Specify your Go version here

      - name: Build binary
        run: |
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o journaldPrometheusExporter-${{ matrix.goos }}-${{ matrix.goarch }} ./  # Customize this with your entrypoint

      - name: Upload binaries as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: journaldPrometheusExporter-${{ matrix.goos }}-${{ matrix.goarch }}
          path: journaldPrometheusExporter-${{ matrix.goos }}-${{ matrix.goarch }}

  release:
    name: Release binaries
    runs-on: ubuntu-latest
    needs: build  # Ensure this runs only after the build job

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            journaldPrometheusExporter-linux-386
            journaldPrometheusExporter-linux-amd64
            journaldPrometheusExporter-linux-arm
            journaldPrometheusExporter-linux-arm64
            journaldPrometheusExporter-darwin-386
            journaldPrometheusExporter-darwin-amd64
            journaldPrometheusExporter-windows-386
            journaldPrometheusExporter-windows-amd64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

